version: '3.9'
services:
  app:
    image: thearturthur/gamp-manager
    container_name: app
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./
        target: /app
    command: [ "python3.10", "app.py" ]
  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./src/prometheus/prometheus-server
        target: /etc/prometheus
  grafana:
    image: "grafana/grafana-enterprise"
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./src/prometheus/grafana
        target: /etc/grafana
  alertmanager:
    image: "quay.io/prometheus/alertmanager"
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - type: bind
        source: ./src/prometheus/alertmanager
        target: /etc/alertmanager