all:
  hosts:
    192.168.1.45
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: '~/.ssh/id_ed25519'
    ansible_ssh_password: 'vagrant'
    ansible_python_interpreter: /usr/bin/python3