---
- name: Install and start Node Exporter
  hosts: ansible_test
  tasks:
    - name: Create node_exporter dir
      become: yes
      file:
        path: '/opt/exporters/node_exporter'
        state: directory
        owner: root
        group: root
      vars:
        ansible_become_password: 'BolgerDan2'
    - name: Install node exporter
      become: yes
      import_role:
        name: cloudalchemy.node_exporter
      vars:
        ansible_become_password: 'BolgerDan2'
        node_exporter_version: latest
        node_exporter_web_listen_address: "0.0.0.0:9100"
        node_exporter_web_telemetry_path: "/metrics"
        node_exporter_textfile_dir: "/opt/exporters/node_exporter/textfile_collector"
        node_exporter_enabled_collectors:
          - systemd
          - textfile:
              directory: "{{ node_exporter_textfile_dir }}"
        #  - filesystem:
        #      ignored-mount-points: "^/(sys|proc|dev)($|/)"
        #      ignored-fs-types: "^(sys|proc|auto)fs$"
        node_exporter_disabled_collectors: [ ]
        # Internal variables.
        _node_exporter_binary_install_dir: "/opt/exporters/node_exporter"
        _node_exporter_system_group: "prometheus"
        _node_exporter_system_user: "{{ _node_exporter_system_group }}"